blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views


app_name = 'blog'

urlpatterns = [
    # path('', PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),

    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    # path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:post_slug>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:pk>/share/', views.post_share, name='post_share_by_email'),

    path('about/', views.about, name='about'),

]

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('home1/', views.home_1, name='home_1'),
    path('home2/', views.home_2, name='home_2'),
]

marketing/urls.py
from django.urls import path
from . import views

app_name = 'marketing'

urlpatterns = [
    path('newsletter/email-list-signup', views.email_list_signup, name='email-list-signup'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify
from django.db import IntegrityError
from .utils import unique_slugify
import re
from django.utils.safestring import mark_safe


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    tags = TaggableManager()

    objects = models.Manager() # The default manager
    published = PublishedManager() # My custom manager

    title = models.CharField(max_length=80)
    # slug = models.SlugField(max_length=200, unique_for_date='date_published')
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    # if I'll use auto_now_add=True I won't be able to change the date so
    # pass the timezone.now function as default value but don't execute it
    date_published = models.DateTimeField(default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')

    class Meta:
        ordering = ('-date_published', )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        unique_slugify(self, self.title)
        super(Post, self).save(**kwargs)

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       args=[self.date_published.year,
                             self.date_published.month,
                             self.date_published.day,
                             self.slug])

    def get_time_to_read(self):
        # result = list(map(lambda x: x.strip(), self.content.split(' ')))
        result = len(re.findall(r'\w+', self.content))
        return result // 150 + 1

    # returns the full url to the instance as a string
    # def get_absolute_url(self):
    #     return reverse('blog:post-detail',
    #                    kwargs={
    #                         'year': self.date_published.year,
    #                         'month': self.date_published.month,
    #                         'day': self.date_published.day,
    #                         'slug': self.slug
    #                         })

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/forms.py
from django import forms
# from pagedown.widgets import PagedownWidget
from .models import Post, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class ShareByEmailForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class PostForm(forms.ModelForm):

    # add html to your form fields
    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.form_class = 'markdown-content'
    #     self.helper.form_id = 'id-exampleForm'
    #     self.helper.form_method = 'post'
    #     self.helper.form_action = 'submit_survey'
    #     self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Post
        fields = ['title', 'tags', 'content']
        # widgets = {
        #     'content': PagedownWidget()
        # }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from taggit.models import Tag
from .models import Post
from .forms import ShareByEmailForm, PostForm, CommentForm
# from pagedown.widgets import PagedownWidget
from marketing.forms import EmailSignupForm


# ListView uses MultipleObjectMixin (therefor you can use methods like is_paginated in the template)
class PostListView(ListView):
    model = Post
    context_object_name = 'posts' # Default: object_list
    # queryset = Post.objects.all() # Default: Model.objects.all()
    # template_name = 'blog/post_list.html' # Default: <app_label>/<model_name>_list.html
    # ordering = ['-date_published'] # change the ordering here or in the model
    paginate_by = 4 # passes page_obj object into the template


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    form = EmailSignupForm()

    # search posts feature
    query = request.GET.get('query')
    if query:
        query = query.strip()
        object_list = object_list.filter(
            Q(title__icontains=query) |
            Q(tags__name__icontains=query) |
            Q(content__icontains=query) |
            Q(author__username__icontains=query)
            ).distinct()
        # distinct() -> no duplicates

    tag = None
    if tag_slug:
        # get the Tag object with the specific tag in the db
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'page': page,
        'posts': posts,
        'tag': tag,
        'section': 'home',
        'form': form,
    }
    return render(request, 'blog/post_list.html', context)


class PostDetailView(DetailView):
    # model = Post
    context_object_name = 'post' # object - default

    # this works but django advises to use get_context_data() !!!
    # self.context["name_to_use"] = "value"

    # def get(self, *args, **kwargs):


    def post(self, *args, **kwargs):
        comment_form = CommentForm(data=self.request.POST or None)
        if comment_form.is_valid():
            self.post = self.get_object()

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = self.post
            # Save the comment to the database
            new_comment.save()

            messages.success(self.request, 'Submitted! Your comment is awaiting moderation')
            return redirect(self.post.get_absolute_url())
        else:
            messages.error(self.request, "Comment wasn't submitted")
            return redirect(self.post.get_absolute_url())


    def get_object(self):
        return get_object_or_404(Post,
                    date_published__year = self.kwargs.get('year'),
                    date_published__month = self.kwargs.get('month'),
                    date_published__day = self.kwargs.get('day'),
                    slug = self.kwargs.get('post_slug'),
                    status = 'published')

    def get_context_data(self, **kwargs):
        # assign the object to the view !!!
        self.post = self.get_object()

        comments = self.post.comments.filter(active=True)

        # List of similar posts
        post_tags_ids = self.post.tags.values_list('id', flat=True)
        similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=self.post.id)

        similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-date_published')[:4]

        context = super().get_context_data(**kwargs)
        context['similar_posts'] = similar_posts
        context['comments'] = comments
        context['comment_form'] = CommentForm()
        return context



class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts' # object_list - default
    paginate_by = 4

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get('username'))

    def get_queryset(self):
        self.user = self.get_object()
        return Post.published.filter(author=self.user).order_by('-date_published')

    def get_context_data(self, **kwargs):
        # assign the object to the view !!!
        self.user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['author'] = self.user
        return context

# post_form.html
# context_object_name = 'form' - default
class PostCreateView(LoginRequiredMixin, CreateView):
    # form_class = PostForm #uncomment if you want to add PagedownWidget
    model = Post
    # specifie the fields in the form OR in the view
    fields = ['title', 'tags', 'content'] # 'status'

    # override the form valid method in order to add the author - the user who is submitting the post
    def form_valid(self, form):
        cd = form.cleaned_data
        form.instance.author = self.request.user
        form.instance.status = 'published' # comment if you want to be able to check the user's posts before publishing them

        # MAKING THE SLUG UNIQUE IS NOW HANDLED IN models.py
        # form.instance.slug = slugify(cd['title'])
        # slug_is_unique = not Post.objects.filter(slug__exact=form.instance.slug).exists()
        # if slug_is_unique:
        return super().form_valid(form)
        # else:
        #     messages.error(self.request, 'Title already exists!')
        #     return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'new-post'
        return context



# post_form.html
# context_object_name = 'form' - default
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'tags', 'content']

    # override the form valid method in order to add the author - the user who is submitting the post
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # will be run by UserPassesTestMixin
    def test_func(self):
        post = self.get_object()
        # the current logged in user == the author of the post
        if self.request.user == post.author:
            return True
        return False


# post_confirm_delete.html
# context_object_name = 'object' - default
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

    def test_func(self):
        post = self.get_object()
        # the current logged in user == the author of the post
        if self.request.user == post.author:
            return True
        return False

# However, you can't use reverse with success_url, because then reverse is called when the module is imported, before the urls have been loaded.
# def get_success_url(self):
#     return reverse('blog:post_list')
# Overriding get_success_url is one option, but the easiest fix is to use reverse_lazy instead of reverse.


def post_share(request, pk):
    post = get_object_or_404(Post, id=pk, status='published')
    sent = False

    if request.method == 'POST':
        form = ShareByEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = f"{cd['name']}({cd['email']}) recommends you {post.title[:25]}... {post.get_time_to_read()} minutes read"

            body = f"Read '{post.title}' at {post_url}\n\n{cd['name']}'s comments:\n\n{cd['comments']}"

            send_mail(subject, body, 'mihainegrisan.cv@gmail.com', [cd['to']])
            sent = True
            messages.success(request, f"Your email was successfully sent to {cd['to']}")

            # This will call the model’s get_absolute_url() method;
            return redirect(post)
        else:
            messages.error(request, "Please check again.")
    else:
        form = ShareByEmailForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }

    return render(request, 'blog/post_share_by_email.html', context)



def about(request):
    return render(request, 'blog/about.html', {'section': 'about'})

blog/templates/blog/_time_to_read.html
{% with time_to_read=post.get_time_to_read %}
  {{ time_to_read }} minute{{ time_to_read|pluralize }} read
{% endwith %}

blog/templates/blog/base.html
{% load static %}
{% load show_latest_posts %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap 4 CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Font Awesome 4.7 -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet"  type='text/css'>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />

  <!-- CSS material design -->
  <!-- <link href="{% static 'blog/material_assets/css/material-kit.css' %}" rel="stylesheet" /> -->

  <!-- My own css for the blog -->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/main.css' %}">

  {% block styles %}{% endblock styles %}


  {% if title %}
    <title>{{ title }}</title>
  {% else %}
    <title>Mihai Blog</title>
  {% endif %}

  {% block head_extra %}{% endblock head_extra %}
</head>
<body>
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v5.0&appId=445334359632844&autoLogAppEvents=1"></script>

  <!-- Back to top button -->
  <a id="back-to-top-button"></a>

  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-light fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'blog:post_list' %}">Mihai Negrisan</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link underline {% if section == 'home' %}active{% endif %}" href="{% url 'blog:post_list' %}">Home</a>
            <a class="nav-item nav-link underline {% if section == 'about' %}active{% endif %}" href="{% url 'blog:about' %}">About</a>
            <div class="underbar"></div>
          </div>

          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link underline {% if section == 'new-post' %}active{% endif %}" href="{% url 'blog:post-create' %}">New Post</a>
              <a class="nav-item nav-link underline {% if section == 'profile' %}active{% endif %}" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link underline {% if section == 'logout' %}active{% endif %}" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link underline" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link underline" href="{% url 'register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>

  <main role="main" class="container">
    <div class="row">
      <div class="col-12 col-lg-9">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="material-icons">clear</i></span>
              </button>
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}{% endblock content %}
      </div>

      {% block post_form %}{% endblock post_form %}

      <div class="col-12 col-lg-3 mt-1 sidebar">

        {% block widget %}{% endblock widget %}

        <div class="card my-4 mt-5 text-center links-inside">
          <h5 class="card-header">Latest Posts</h5>
          <div class="card-body">
            <ul class="list-unstyled mb-0">
              {% show_latest_posts 3 %}
            </ul>
          </div>
        </div>

        <!-- Tabs with icons on Card -->
        <div class="card card-nav-tabs mt-5">
          <div> <!-- class="card-header card-header-primary" -->
            <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" data-tabs="tabs">
                  <li class="nav-item">
                    <a class="nav-link active" href="#profile" data-toggle="tab">
                      <i class="material-icons">face</i>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#messages" data-toggle="tab">
                      <i class="material-icons">chat</i>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#settings" data-toggle="tab">
                      <i class="material-icons">build</i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="tab-content text-center">
              <div class="tab-pane active" id="profile">
                <p> I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that&#x2019;s a responsibility...</p>
              </div>
              <div class="tab-pane" id="messages">
                <p> I think that&#x2019;s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers.</p>
              </div>
              <div class="tab-pane" id="settings">
                <p>I think that&#x2019;s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it&#x2019;s supposed ...</p>
              </div>
            </div>
          </div>
        </div>
        <!-- End Tabs with icons on Card -->

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4 mt-5 text-center all-tags">
          <h5 class="card-header">All Tags</h5>
          <div class="card-body">
            <div class="row">
              {% for tag in tags %}
                <a class="mr-2 mb-2 underline" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                  <button type="button" class="btn btn-warning btn-sm">
                    {{ tag.name }} <span class="badge badge-text badge-primary">{{ tag.num_times }}</span>
                  </button>
                  <!-- <span class="badge-text">{{ tag.name }} {{ tag.num_times }}</span> -->
                </a>
                {# {% if not forloop.last %}, {% endif %} #}
              {% endfor %}
              <!-- <button type="button" class="btn btn-sm btn-warning">
                Messages <span class="badge badge-light">4</span>
              </button> -->
            </div>
          </div>
        </div>

        <!-- Old Sidebar -->
        <!-- <div class="content-section">
          <h3>Sidebar</h3>
          <p class='text-muted'>Not configured yet
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Subscribe</li>
              <li class="list-group-item list-group-item-light">Tags</li>
              <li class="list-group-item list-group-item-light ">Announcements</li>
              <li class="list-group-item list-group-item-light">About</li>
              <li class="list-group-item list-group-item-light">Contact</li>
            </ul>
          </p>
        </div> -->
      </div>
    </div>
  </main>

  <!-- Footer -->
<footer class="page-footer font-small unique-color-dark">
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="#"> mihainegrisan.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- Syntax highlight -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/10.0.0/markdown-it.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>
  <script src="{% static 'blog/js/app.js' %}"></script>

</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load urlify %}
{% load markdownify %}
{% load crispy_forms_tags %}

{% block styles %}
  <!-- Stylesheet for syntax highlight -->
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/default.css' %}">
{% endblock styles %}

{% block content %}
  <article class="media">
    <div class="card my-4">
      <!-- <h5 class="card-header">Search</h5> -->
      <div class="card-body">
        <div class="media-body">
          <div class="article-metadata">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
            <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_published|date:"N d, Y" }}</small>
            <!-- if the author is the current logged in user -->

            <div class="float-xs-none float-sm-right">
              {% if post.author == user %}
                <a class="btn btn-outline-success btn-sm mt-1 mb-1" href="{% url 'blog:post-update' post.id %}">Update</a>
                <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' post.id %}">Delete</a>
              {% endif %}
              <a class="btn btn-outline-primary btn-sm mt-1 mb-1" href="{% url 'blog:post_share_by_email' post.id %}">Share</a>
            </div>

          </div>
          <h2 class="article-title">
            <br>
            {{ post.title|capfirst }}
            <br><br>
          </h2>
          <div class="article-content post-detail-item">{{ post.content|markdownify|safe }}</div>

          <br><br>

          <!-- Like and Share links -->
          <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width="" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
          <div class="row">
            <div class="col-md-12">
              <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-width="100%" data-numposts="5"></div>
            </div>
          </div>

          <!-- <div>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">Share on Facebook</a>
            <a href="https://twitter.com/home?status={{ post.title|urlify }}%20{{ request.build_absolute_uri }}" target="_blank">Share on Twitter</a>
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ post.title|urlify }}&summary={{ post.title|urlify }}&source={{ request.build_absolute_uri }}" target="_blank">Share on Linkedin</a>
            <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ post.title|urlify }}" target="_blank">Share on Reddit</a>
          </div> -->
        </div>
      </div>
    </div>
  </article>

  <!-- Comments -->
  <article class="media">
    <div class="card my-2">
      <div class="card-body">
        <div class="article-metadata mb-4">
          <h2>{{ comments.count }} comments</h2>
        </div>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% if not forloop.last %}
          <hr>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </article>

  <article class="media">
    <div class="card my-4">
      <div class="card-body">
        <div class="article-metadata mb-4">
          <h3>Leave a comment</h3>
        </div>
        <form method="post" style="margin-top: 1.3em;">
           {{ comment_form | crispy }}
           {% csrf_token %}
           <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
      </div>
    </div>
  </article>
{% endblock content %}


{% block widget %}
  <div class="card my-4 mt-5 text-center links-inside">
    <h5 class="card-header">Similar Posts</h5>
    <div class="card-body">

      <ul class="list-unstyled mb-0">
        {% for post in similar_posts %}
          <li>
              <a class="underline" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </li>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock widget %}

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}
{% load markdownify %}

{% block content %}
  <!-- to get the username that is passed in to the url -->
  <div class="mb-3 d-flex flex-column align-items-center">
    <img class="rounded-circle article-img-user-posts mb-3" src="{{ author.profile.image.url }}" alt="profile-pic">
    <h1>{{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
  </div>
  {% for post in posts %}
    <article class="media">
      <div class="card my-4">
        <div class="card-body">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_published|date:"N d, Y" }}</small>
              <small><strong>Tags:</strong>
                  {% for tag in post.tags.all %}
                    <a class="badge badge-warning text-dark" href="{% url 'blog:post_list_by_tag' tag.slug %}">
                      <span class="badge-text">{{ tag.name }}</span>
                    </a>
                  {% endfor %}
              </small>
              <span class="badge badge-danger text-white badge-text align-middle">
                {% include 'blog/_time_to_read.html' %}
              </span>
            </div>
            <h2><a class="article-title underline" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|markdownify|safe|truncatewords_html:50 }}</p>
          </div>
        </div>
      </div>
    </article>
  {% endfor %}

  {% include 'blog/_pagination.html' %}

{% endblock content %}